#!/bin/bash
set -Eeuo pipefail

# FORMAT_FILES=$(find lib src tests -type f -name '*.[ch]')

clang-format --verbose -i $(find lib src tests -type f -name '*.[ch]')
clang-format --verbose --dry-run --Werror $(find lib src tests -type f -name '*.[ch]')
